name: Build b2

on:
  push:
    branches:
      - master
      - wip/master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: make github_ci_ubuntu
  build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: make github_ci_windows
  build-macos-x64:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run:
        - make github_ci_macos_homebrew
        - make github_ci_macos_homebrew_ffmpeg
        - make github_ci_macos_x64
  build-macos-arm:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run:
        - make github_ci_macos_homebrew
        - make github_ci_macos_homebrew_ffmpeg
        - make github_ci_macos_arm
