name: Build on Linux

on:
  push:
    branches:
      - master
      - wip/master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: make github_ci
